"""
DATA MODELS MODULE

This file defines the Pydantic models used for API requests, responses,
and internal chat storage. FastAPI uses these to validate incoming JSON
and to serialize responses; the chat service uses them when saving/loading sessions.

MODELS:
- ChatRequest      - Body of POST /chat and POST /chat/realtime (message + optional session_id).
- ChatResponse     - Body returned by both chat endpoints (response text + session_id).
- ChatMessage      - One message in a conversation (role + content). Used inside ChatHistory.
- ChatHistory      - Full conversation: session_id + list of ChatMessage. Used when saving to disk.
"""

from pydantic import BaseModel, Field
from typing import List, Optional

# MESSAGE AND REQUEST/RESPONSE MODELS

class ChatMessage(BaseModel):
    """
    A single message in a conversation ( user or assisstant).
    stored in order inside a session. No timestamp; order defines chronology.
    """
    role: str
    content : str
    
    
class ChatRequest(BaseModel):
    """
    message: Required. The user's question or message.
             Must be 1-32000 characters (validated by Pydantic;
             empty or too long returns 422).

    session_id: Optional. If omitted, the server creates a new session
                and returns its ID. If provided, the server uses it
                (and loads from disk if that session exists).
    """
    # "..." means required; min/max length prevent empty input and token overflow.

    message: str = Field(..., min_length=1, max_length=32_000)
    session_id: Optional[str] = None


class ChatResponse(BaseModel):
    """
    Response body for POST /chat and POST /chat/realtime.

    response: The assistant's reply text.
    session_id: The session this message belongs to;
                send it on the next request to continue.
    """

    response: str
    session_id: str


class ChatHistory(BaseModel):
    """
    Internal model for a full conversation:
    session_id plus ordered list of messages.

    Used when saving a session to disk
    (chat_service serializes this to JSON).
    """

    session_id: str
    messages: List[ChatMessage]


class IntentRequest(BaseModel):
    """
    Request model for POST /intent.
    query: The raw user voice/text query to classify and route.
    session_id: Optional session identifier for maintaining chat/memory context.
    """
    query: str = Field(..., min_length=1, max_length=32_000)
    session_id: Optional[str] = None


class IntentTaskItem(BaseModel):
    """
    Individual task unit within an intent execution plan.
    """
    intent_type: str  # 'automation', 'chat', or 'realtime'
    action: Optional[str] = None
    target: Optional[str] = None
    parameters: Optional[dict] = None
    query: Optional[str] = None
    response: Optional[str] = None


class IntentResponse(BaseModel):
    """
    Response model for POST /intent.
    intent_type: 'automation', 'chat', 'realtime', or 'compound'.
    action: For single automation, the extracted action (e.g. 'open_app', 'play_music').
    target: For single automation, the target subject (e.g. 'chrome', 'believer').
    parameters: Optional dict with extra details (e.g. reminder time, etc).
    response: For chat/realtime (or combined compound answer), the text answer generated by the brain.
    tasks: Optional ordered list of IntentTaskItem for multi-command execution.
    session_id: Optional session ID used for the query.
    """
    intent_type: str
    action: Optional[str] = None
    target: Optional[str] = None
    parameters: Optional[dict] = None
    response: Optional[str] = None
    tasks: Optional[List[IntentTaskItem]] = None
    session_id: Optional[str] = None